"use client";

import { useEffect, useState } from "react";
import { site } from "@/data/site";
import { CAPTCHA_ANSWER_FIELD, CAPTCHA_TOKEN_FIELD } from "@/lib/forms";
import { Field } from "./Field";
import styles from "./Form.module.css";

type Challenge = { svg: string; token: string };

async function requestChallenge(): Promise<Challenge> {
  const response = await fetch("/api/captcha", { cache: "no-store" });
  if (!response.ok) throw new Error(`captcha ${response.status}`);
  const data = (await response.json()) as Partial<Challenge>;
  if (typeof data.svg !== "string" || typeof data.token !== "string") throw new Error("captcha payload");
  return { svg: data.svg, token: data.token };
}

type MathCaptchaProps = {
  /** Lets the parent form focus this field when it's missing. */
  inputId: string;
  error?: string;
  /** Called with the answer as the visitor types (and with "" when the sum is replaced). */
  onAnswer?: (answer: string) => void;
  onBlur?: () => void;
};

/**
 * "What is 5 + 4?" — the sum is drawn on our server (see /api/captcha) and checked there
 * again on submit. The parent remounts this component (new `key`) to load a fresh question.
 */
export function MathCaptcha({ inputId, error, onAnswer, onBlur }: MathCaptchaProps) {
  const [round, setRound] = useState(0);
  const [challenge, setChallenge] = useState<Challenge | null>(null);
  const [failed, setFailed] = useState(false);
  const [answer, setAnswer] = useState("");

  useEffect(() => {
    let active = true;
    requestChallenge()
      .then((next) => {
        if (!active) return;
        setChallenge(next);
        setFailed(false);
      })
      .catch(() => {
        if (active) setFailed(true);
      });
    return () => {
      active = false;
    };
  }, [round]);

  const refresh = () => {
    setChallenge(null);
    setFailed(false);
    setAnswer("");
    onAnswer?.("");
    setRound((r) => r + 1);
  };

  const describedBy = error ? `${inputId}-error` : `${inputId}-hint`;

  return (
    <Field id={inputId} label="Security check" error={error}>
      <div className={styles.captchaRow}>
        {challenge ? (
          <span
            className={styles.question}
            role="img"
            aria-label="Sum to solve"
            // Generated by svg-captcha on our own server: vector outlines only, no text or scripts.
            dangerouslySetInnerHTML={{ __html: challenge.svg }}
          />
        ) : (
          <span className={`${styles.question} ${failed ? styles.questionFailed : styles.questionLoading}`} aria-live="polite">
            {failed ? "Couldn't load — try again" : <span className="sr-only">Loading the security question…</span>}
          </span>
        )}
        <span className={styles.equals} aria-hidden="true">
          =
        </span>
        <input
          id={inputId}
          name={CAPTCHA_ANSWER_FIELD}
          value={answer}
          onChange={(e) => {
            const next = e.target.value.replace(/\D/g, "").slice(0, 3);
            setAnswer(next);
            onAnswer?.(next);
          }}
          onBlur={onBlur}
          inputMode="numeric"
          maxLength={3}
          autoComplete="off"
          aria-required="true"
          placeholder="?"
          aria-invalid={error ? true : undefined}
          aria-describedby={describedBy}
          className={`${styles.input} ${styles.answer}`}
        />
        <button type="button" className={styles.refresh} onClick={refresh} aria-label="Show a different sum">
          <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M16.5 10a6.5 6.5 0 1 1-1.9-4.6M16.5 3.5v3.6h-3.6" />
          </svg>
        </button>
        <input type="hidden" name={CAPTCHA_TOKEN_FIELD} value={challenge?.token ?? ""} />
      </div>
      {!error &&
        (failed ? (
          // Without a question the form can't be sent, so offer the direct lines instead
          <p id={`${inputId}-hint`} className={styles.captchaHint}>
            Our server can&rsquo;t be reached right now. Try again, or call <a href={site.phoneHref}>{site.phone}</a> or email{" "}
            <a href={`mailto:${site.email}`}>{site.email}</a>.
          </p>
        ) : (
          <p id={`${inputId}-hint`} className={styles.captchaHint}>
            Add the two numbers to show you&rsquo;re not a bot.
          </p>
        ))}
    </Field>
  );
}
